[theme]
base = "light"
primaryColor = "#0877B9"
backgroundColor = "#F6F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#24313B"
borderColor = "#DCE4E8"
showWidgetBorder = true
baseRadius = "medium"
buttonRadius = "medium"

[client]
toolbarMode = "minimal"
showErrorDetails = "none"
